spring.application.name=currency_conversion
server.port=${PORT:8080}

openexchangerates.app-id=${OPENEXCHANGERATES_APP_ID:a3e19efea0214dd28d8d4921708a8562}

spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb+srv://Dhivakarever:Dhiva2167@conversion.fwndu50.mongodb.net/currencydb?retryWrites=true&w=majority}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:humorous-weasel-307207.upstash.io}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:gQAAAAAABLAHAAIgcDFlYTEyODQ1OTQ1MWM0ZDAxOWUyZjI4OGYwNmY3ODMzNg}
spring.data.redis.ssl.enabled=true

spring.cache.type=redis
spring.cache.redis.time-to-live=3600000
spring.cache.redis.cache-null-values=false
